# Generated by Django 4.2.26 on 2026-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correct_text',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный ответ (текст)'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ID создателя'),
        ),
        migrations.AlterField(
            model_name='test',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ID создателя'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
