# Generated by Django 5.2.8 on 2025-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID создателя'),
        ),
    ]
